// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PopulationData
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("countryISO3")]
        public string CountryIso3 { get; set; }

        [JsonProperty("countryName")]
        public string CountryName { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("population")]
        public long Population { get; set; }

        [JsonProperty("populationFormatted")]
        public string PopulationFormatted { get; set; }

        [JsonProperty("growthRate")]
        public double GrowthRate { get; set; }

        [JsonProperty("density")]
        public double Density { get; set; }

        [JsonProperty("densityUnit")]
        public string DensityUnit { get; set; }

        [JsonProperty("urbanPercent")]
        public double UrbanPercent { get; set; }

        [JsonProperty("ruralPercent")]
        public double RuralPercent { get; set; }

        [JsonProperty("urbanPopulation")]
        public long UrbanPopulation { get; set; }

        [JsonProperty("ruralPopulation")]
        public long RuralPopulation { get; set; }

        [JsonProperty("lifeExpectancy")]
        public double LifeExpectancy { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTimeOffset LastUpdated { get; set; }
    }
}
